import numpy as np

from utils import *
import scipy.io
import scipy.sparse as sparse
from scipy.sparse import csgraph
import logging
import theano

logger = logging.getLogger(__name__)
theano.config.exception_verbosity = 'high'


class DataHolder():
    def __init__(self, name):
        super(DataHolder, self).__init__()
        self.name = name

        self.DA_own = []
        self.A_own = []
        self.A_sparse = []
        self.A_other = []


        self.vol = 0.0

        self.D = []
        self.L = []

        self.D_sparse = []
        self.L_sparse = []

        self.M_sparse = []

        self.PDAQ = []
        self.PDA2Q = []

        # Alice
        self.random_matrices = []
        self.T = []
        self.T_ = []
        self.residual_1 = []
        self.residual_2 = []

        # Bob
        self.C = []
        self.W = []

    def generate_random_adjacency_matrix(self, size, if_sparse=False):
        res = np.random.randint(2, size=(size, size))
        res = np.triu(res)
        res = res + res.T - np.diag(res.diagonal())
        if if_sparse:
            return sparse.csc_matrix(res)
        return res

    def load_test_data(self, size):
        '''
        load test matrix to test the code
        :param size:size of initalize
        :return:
        '''
        self.A_own = self.generate_random_adjacency_matrix(size, if_sparse=False)
        self.vol = float(self.A_own.sum())
        # self.L, self.D = csgraph.laplacian(self.A_own, normed=True, return_diag=True)
        self.D = np.array(sum(self.A_own), dtype=float)
    def load_test_data_1000(self, size):
        self.A_own = np.load("datasets/test_"+self.name+"_1000.npy")
        self.vol = float(self.A_own.sum())
        # self.L, self.D = csgraph.laplacian(self.A_own, normed=True, return_diag=True)
        self.D = np.array(sum(self.A_own), dtype=float)

    def load_test_data_block(self, size, block_size):
        res = self.A_own = self.generate_random_adjacency_matrix(size, if_sparse=False)
        self.vol = float(self.A_own.sum())
        # self.L, self.D = csgraph.laplacian(self.A_own, normed=True, return_diag=True)
        self.D = np.array(sum(self.A_own), dtype=float)
        self.A_sparse = dok_matrix(self.A_own)
        self.A_own = block_matrix_splitter(self.A_own, name=self.name, diag=False, block_size=block_size)
        return res

    def load_test_data_block_1000(self, size, block_size):
        self.A_own = np.load("datasets/test_"+self.name+"_1000.npy")
        self.vol = float(self.A_own.sum())
        # self.L, self.D = csgraph.laplacian(self.A_own, normed=True, return_diag=True)
        self.D = np.array(sum(self.A_own), dtype=float)
        self.A_sparse = dok_matrix(self.A_own)
        self.A_own = block_matrix_splitter(self.A_own, name=self.name, diag=False, block_size=block_size)

    def load_test_data_memmap(self, size):
        D = np.memmap("matrices/D.npy")
        self.A_own = self.generate_random_adjacency_matrix(size, if_sparse=False)
        self.vol = float(self.A_own.sum())
        # self.L, self.D = csgraph.laplacian(self.A_own, normed=True, return_diag=True)
        self.D = np.array(sum(self.A_own), dtype=float)

    def path_sampling(self, A, T, m, if_block, block_size):
        """
        path sampling method for fednetsmf
        and compute L and D of the sparse graph
        :param T: window size
        :param m: non-zero number
        :return:
        """
        self.A_sparse = path_sampling(A, T, m)
        self.A_sparse = self.A_sparse.todense()
        self.D_sparse = np.array(sum(self.A_sparse), dtype=float)
        self.L_sparse = np.diag(self.D_sparse - self.A_sparse)
        if if_block:
            # transform the big matrices into blocks
            self.A_sparse = block_matrix_splitter(self.A_sparse, name=f"A_sparse_{self.name}", diag=False, block_size=block_size)
            self.D_sparse = block_matrix_splitter(self.D_sparse, name=f"D_sparse_{self.name}", diag=True, block_size=block_size)
            self.L_sparse = block_matrix_splitter(self.L_sparse, name=f"L_sparse_{self.name}", diag=False, block_size=block_size)

    def calculate_M(self, D, O):
        """
        calculate and mask M matrix
        :param D: Degree diag matrix of complete graph
        :param O: Mask matrix generated by mask server
        :return:
        """
        self.M_sparse = np.dot(np.diag(D ** -1), np.add(self.D, -self.L_sparse)).dot(np.diag(D ** -1)) # calculate M
        self.M_sparse = np.dot(self.M_sparse, O) # calcluate M*O get mask of M

    def calculate_M_block(self, D, O, block_size):
        """
        calculate and mask M matrix (input and output block matrix)
        :param D: (block) Degree diag matrix of complete graph
        :param O: (block) Mask matrix generated by mask server
        :return:
        """
        tmp1 = diag_block_add(self.L_sparse, self.D, "tmp1", "-+")
        D_ = block_matrix_splitter(np.diag(D), name=f"D_sparse_{self.name}", diag=True, block_size=block_size)
        tmp2 = block_dot(D_, tmp1, block_size=block_size, name="tmp2")
        tmp3 = block_dot(tmp2, D_, block_size=block_size, name="tmp3")
        self.M_sparse = block_dot(tmp3, O, block_size=block_size, name=f"M_sparse_{self.name}")

    def compute_B_block(self, Q, block_size):
        # TODO check qr分解看一下mode是不是对的
        # TODO check B block的计算可能需要重写
        self.B = block_dot(Q, self.M_sparse, name=f"B_{self.name}", block_size=block_size)












    def get_DA(self, D):
        self.DA_own = np.dot(np.diag(D ** -1), self.A_own)

    def get_DA_block(self, D):
        self.DA_own = diag_block_dot(self.A_own, D, "DA_" + self.name, dot_side="left", inverse=True)

    def load_data(self, path):
        '''
        load .mat sparse matrices
        :param path:
        :return:
        '''
        data = scipy.io.loadmat(path)
        logger.info("loading mat file %s", path)
        # print(data.keys())
        # print(data['Problem'][0][0][2])
        # matrix = data['Problem'][0][0][2]
        matrix = data['network']
        self.A_own = matrix
        # print(sum(self.A_own))
        self.vol = float(self.A_own.sum())
        self.D = np.array(sum(self.A_own), dtype=float)
    def load_data_block(self, path, block_size):
        data = scipy.io.loadmat(path)
        logger.info("loading mat file %s", path)
        # print(data.keys())
        print(data['network'].shape)
        matrix = data['network'].todense()

        # print(data['Problem'][0][0][2].shape)
        # matrix = data['Problem'][0][0][2].todense()
        self.A_own = matrix
        # print(sum(self.A_own))
        self.vol = float(self.A_own.sum())
        self.D = np.array(sum(self.A_own), dtype=float)
        self.A_own = block_matrix_splitter(self.A_own, name=self.name, diag=False, block_size=block_size)

    def calculate_size(self):
        return self.A_own.shape[0]

    def get_residual_1(self, residual):
        self.residual_1 = residual

    def get_residual_2(self, residual):
        self.residual_2 = residual

    def calculate_residual_1(self):
        self.residual_1.append(self.DA_own - self.random_matrices[0])
        self.residual_1.append(self.DA_own - self.random_matrices[1])
        return self.residual_1

    def calculate_residual_1_block(self):
        self.residual_1.append(
            diag_block_add(self.DA_own, self.random_matrices[0], "residual_1_0_" + self.name, negative="+-"))
        self.residual_1.append(
            diag_block_add(self.DA_own, self.random_matrices[1], "residual_1_1_" + self.name, negative="+-"))
        return self.residual_1

    def calculate_residual_2(self):
        self.residual_2.append(self.DA_own - self.random_matrices[0])
        self.residual_2.append(self.DA_own - self.random_matrices[1])
        return self.residual_2

    def calculate_residual_2_block(self):
        self.residual_2.append(
            diag_block_add(self.DA_own, self.random_matrices[0], "residual_2_0_" + self.name, negative="+-"))
        self.residual_2.append(
            diag_block_add(self.DA_own, self.random_matrices[1], "residual_2_1_" + self.name, negative="+-"))
        return self.residual_2

    def calculate_PDAQ(self, P, D, Q):
        # self.PDAQ = np.dot(P,sparse.diags(D**-1)).dot(self.A_own).dot(Q)
        self.PDAQ = np.dot(P, np.diag(D ** -1)).dot(self.A_own).dot(Q)

    def calculate_PDAQ_block(self, P, D, Q):
        tmp1 = diag_diag_block_dot(P, D, "tmp1", dot_side="right", inverse=True)
        tmp2 = diag_block_dot(self.A_own, tmp1, "tmp2", dot_side="left")
        self.PDAQ = diag_block_dot(tmp2, Q, "PDAQ_" + self.name, dot_side="right")

    def calculate_PDA2Q(self, P, D, Q):
        # DA = np.dot(sparse.diags(D**-1),self.A_own)
        DA = np.dot(np.diag(D ** -1), self.A_own)
        DA2 = np.dot(DA, DA)
        self.PDA2Q = np.dot(P, DA2).dot(Q)

    # Alice
    def get_random_matrices(self, random_matrices):
        self.random_matrices = random_matrices

    def get_T(self, T):
        self.T = T

    def calculate_W(self):
        self.T_ = random_matrix(self.calculate_size())
        return np.dot(self.random_matrices[0], self.residual_2[1]) \
               + np.dot(self.residual_2[0], self.random_matrices[1]) \
               + np.dot(self.DA_own, self.DA_own) \
               - self.T_

    def calculate_W_block(self, size, block_size):
        self.T_ = generate_block_random_martic(int(size / block_size), block_size, "T_")
        tmp1 = diag_block_dot(self.residual_2[1], self.random_matrices[0], "tmp1", dot_side="left")
        tmp2 = diag_block_dot(self.residual_2[0], self.random_matrices[1], "tmp2", dot_side="right")
        tmp3 = block_dot(self.DA_own, self.DA_own, block_size, "tmp3")
        tmp4 = block_add(tmp1, tmp2, block_size, "tmp4")
        tmp5 = block_add(tmp3, tmp4, block_size, "tmp5")
        return diag_block_add(tmp5, self.T_, "W", negative="+-")

    def output_Ts(self):
        # return sparse.csc_matrix(self.T+self.T_)
        return self.T + self.T_
    def output_Ts_block(self):
        return diag_diag_block_add(self.T, self.T_, "Ts", "++")

    def output_Ts_block(self):
        return diag_diag_block_add(self.T, self.T_, "Ts", negative="++")

    # Bob
    def get_C(self, C):
        # self.C = sparse.csc_matrix(C)
        self.C = C

    def get_W(self, W):
        # self.W = sparse.csc_matrix(W)
        self.W = W

    def output_U(self):
        a = np.dot(self.residual_1[0], self.DA_own)
        b = np.dot(self.DA_own, self.residual_1[1])
        c = np.dot(self.DA_own, self.DA_own)
        d = np.add(np.add(a, b), c)
        res = np.add(d, self.W)
        res = np.add(res, self.C)
        return res

    def output_U_block(self, block_size):
        tmp1 = block_dot(self.residual_1[0], self.DA_own, block_size, "tmp1")
        tmp2 = block_dot(self.DA_own, self.residual_1[1], block_size, "tmp2")
        tmp3 = block_dot(self.DA_own, self.DA_own, block_size, "tmp3")
        tmp4 = block_add(tmp1, tmp2, block_size, "tmp4")
        tmp5 = block_add(tmp3, tmp4, block_size, "tmp5")
        tmp6 = block_add(tmp5, self.W, block_size, "tmp6")
        return diag_block_add(tmp6, self.C, "U", "++")
